######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 21 20:28:21 2009
######################################################################
OBJECTS_DIR=.obj
PKGCONFIG += sdl
LIBS += -lSDL -lSDLmain
TEMPLATE = app
TARGET =  test
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cengine.h cmyengine.h
SOURCES += cengine.cpp cmyengine.cpp main.cpp
